spring.application.name=demogw
server.port=9090

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/spring-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/spring-realm/protocol/openid-connect/certs}

spring.cloud.gateway.mvc.routes[0].id=ms-medico-route
spring.cloud.gateway.mvc.routes[0].uri=${MEDICO_URI:http://localhost:8083}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/ms-medico/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.mvc.routes[1].id=ms-cita-route
spring.cloud.gateway.mvc.routes[1].uri=${CITA_URI:http://localhost:8084}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/ms-cita/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1