spring.application.name=demogw
server.port=9090

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Keycloak OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/spring-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/spring-realm/protocol/openid-connect/certs}

# Ruta hacia ms-inventario
spring.cloud.gateway.mvc.routes[0].id=ms-inventario-route
spring.cloud.gateway.mvc.routes[0].uri=${INVENTARIO_URI:http://localhost:8083}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/ms-inventario/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1

# Ruta hacia ms-pedido
spring.cloud.gateway.mvc.routes[1].id=ms-pedido-route
spring.cloud.gateway.mvc.routes[1].uri=${PEDIDO_URI:http://localhost:8084}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/ms-pedido/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1